export const element = Symbol('element')
export const context = Symbol('context')
export const methods = Symbol('methods')
export const created = Symbol('created')
export const updated = Symbol('updated')
export const components = Symbol('components')

export const style = Symbol('style')
export const data = Symbol('data')
export const attr = Symbol('attr')
export const value = Symbol('value')
export const classList = Symbol('classList')
export const events = Symbol('events')
